### PR TITLE
Adjust SO page for 1920px screen resolution

### PR DESCRIPTION
**Pull request by AndyPLsql**
Hello!
Your extension is awesome, but for me there is not enough function to adjus SO page for FullHD resolution.
I added it.
Maybe SO has this function but I didn't find it.
Before:
image

After changes:
image

Thanks!

### CODE REVIEW

**Comment by AnthoPakPak** [comment]
Hey, thanks for your contribution! I'll try to review and merge it soon.

I've just made some quick tests with this implementation, and in my case it led to create lateral scrolling, which isn't good.
By tweaking some values, I got better results:
- Removing `container.style.margin = "0 60px"`
- Setting `document.getElementById("content").style.maxWidth` to 95% instead of 100%
- Setting `container.style.maxWidth` to 2000px instead of 1843px. Unless there is a good reason for setting it to this value?

What do you think?

**Comment by AndyPLsql** [comment]
Hi! It good that you interested in contributions.
I think it best to do these settings user configurable.
I'll try your changes and try to add extra settings as soon as posible.
Thanks!

**Comment by AndyPLsql** [comment]
I added changes in settings. Now users can setup custom width. Thanks.

**Comment by AnthoPakPak** [comment]
Well done adding this customizable field. Also, thanks for noticing the overlap, with left menu. I've have set the SO Settings to disable this menu (which I find totally useless), so I didn't noticed.

I've just tried your fork, it works well. But as soon as you reduce window size, it will lead to create horizontal scroll (probably caused by `container.style.margin`). What would be good is that the main SO container takes the full width, but it should not somehow break the layout when reducing window size.

I've made some attempts on my side, and I think I've found some settings which work for any screen size, support window resizing, don't overlap, and don't create horizontal scroll. Here are the changes:
image
(both `maxWidth` are set to `100%`, and `margin` is replaced by `padding`)

Can you try to see how it goes on your side, and if it wouldn't be better than an explicit user pref?

**Comment by AnthoPakPak** [comment]
In your screenshot it seems you're using `margin` instead of suggested `padding`. In my tests, `margin` was what caused too wide width. Can you double check?

**Comment by AndyPLsql** [comment]
Yes, you are right.
I rechecked and your solutions is the best.
Additionnaly I changed paddging value to "0 0 0 70px". Now page have maximal possible size.
image

**Comment by AnthoPakPak** [comment]
That's nice.
I guess it would be a good idea to keep a user pref to choose the max percent width % (this one `document.getElementById("content").style.maxWidth`), as you did with px before.
I personally find 100% being too wide, but 80% is good on my screen. So let's let the user choose what he prefers :)

I can re-add this setting when I'll review your PR.

**Pull request merged**
